server:
  port: 8082
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: icecream-orders-service
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic: ice-cream-orders
    template:
      default-topic: ice-cream-orders
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url : http://localhost:8081
      value:
        subject:
          name:
            strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy