server:
  port: 8083

spring:
  application:
    name: icecream-orders-consumer
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic: ice-cream-orders
    template:
      default-topic: ice-cream-orders
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: icecream-orders-listener-group
      auto-offset-reset: earliest
    properties:
      schema.registry.url : http://localhost:8081
      specific.avro.reader: true
      value:
        subject:
          name:
            strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy